### ISSUE TITLE
Improve the installation process

### ISSUE THREAD

**Issue by jayfoad** [Dyalog/dyalog-jupyter-kernel#1]
1. readme.txt tells you to install Anaconda, but this is not necessary. Any Python 3 + Jupyter installation should work.

2. You should be able to install with just "pip install ." (or similar invocation of standard Python package installer tools).

**Comment by jayfoad** [comment]
1. I've added README.md which explains this better. Should probably remove the old readme.txt.

**Comment by abrudz** [comment]
Old readme.txt has been removed, and new README.md mentions that installling Python 3 and Jupyter is enough.
