### ISSUE TITLE
Value error when running notebook (⎕LX)

### ISSUE THREAD

**Issue by jamesheslip** [Dyalog/dyalog-jupyter-kernel#11]
The latent expression in dyalog_kernal\init.dws is:
`hereDir←⊃⎕NPARTS⎕WSID⋄(⍎⊃2⎕FIX'file://',hereDir,'init.dyalog')hereDir`

`(⊃2⎕FIX'file://',hereDir,'init.dyalog')hereDir` returns:
> I C:\Users\james\Dropbox\Study\dyalog-jupyter-kernel\dyalog_kernel\

Should this not be `(2⎕FIX'file://',hereDir,'init.dyalog')hereDir`?
>  Init  C:\Users\james\Dropbox\Study\dyalog-jupyter-kernel\dyalog_kernel\ 

By executing the first line I get back when running the notebook:
`⍎VALUE ERROR
      I`

What is the purpose of the `⊃`?

**Comment by abrudz** [comment]
Should be fixed now.

According to [the documentation](http://help.dyalog.com/15.0/Content/Language/System%20Functions/fix.htm), `2⎕FIX` should (shyly) return *a vector of character vectors, containing the names of all of the objects that have been established*, so `⊃` is to pick the first (and only) name which `⍎` then converts to a function that is then applied to `hereDir`.

However, in Dyalog 15.0 there is a bug causing `2⎕FIX` to return (no shyly) a simple character vector when fixing a single function from a file. It doesn't happen when fixing from a vector of character vectors.

I've logged this issue against Dyalog 15.0.
