### ISSUE TITLE
Clicking on 'restart kernel' causes an aplcore dump

### ISSUE THREAD

**Issue by romilly** [Dyalog/dyalog-jupyter-kernel#2]
Jupyter users coming form a Python background may well click on 'restart kernel', which causes a core dump.

After that you have to restart jupyter, and may have lost some work.

**Comment by jayfoad** [comment]
I've just tried this with a 64-bit Unicode 16.0.33149 interpreter on Linux, and I don't see a problem. What platform are you running on? And what versions of... everything?

**Comment by romilly** [comment]
64-bit Unicode Dyalog APL/S-64 Version 16.0.31812; I'll update and see if that fixes the problem.

Running on Linux Mint 18.3 Sylvia 64-bit, Kernel Linux 4.13.0-43-generic x86_64

**Comment by romilly** [comment]
The latest non-beta version I can see on MyDyalog is Dyalog APL/S-64 Version 16.0.32742 but installing that has solved the problem. Thanks!

**Comment by abrudz** [comment]
Does not appear to be a problem any more.
