### ISSUE TITLE
Orphaned interpreters laying around

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/dyalog-jupyter-kernel#51]
Once the kernel is hosed, the associated interpreter task is left as an orphan.  Parentless, wandering the streets, lonely... it's very sad.

**Comment by RojerGS** [comment]
I also experience this issue, although I can't vouch for the feelings of the associated interpreter task.

**Comment by rikedyp** [comment]
If you use the kernel interface to shut down running kernels, then Dyalog exits correctly. It seems the destructor doesn't do its job when the kernel is hosed. I'm not sure what can be done about this.

**Comment by abrudz** [comment]
Is there some way to detect from the APL side that the connection has been lost, e.g. by polling the kernel? If so, then we can have a Timer that checks once a minute and simply shuts the interpreter down if there's no connection.

**Comment by abrudz** [comment]
Then I believe adding `'Event'('Timer' '⍎{~⍵:⎕OFF}3501⌶⍬')⎕WS⍨'⎕SE.SelfCheck'⎕WC'Timer' 60E3` to dyalog_kernel/init.dyalog will shut the kernel down within a minute if it loses connection.
