### ISSUE TITLE
Wanting to install into latest miniconda python 3.9?

### ISSUE THREAD

**Issue by Bazmundi** [Dyalog/dyalog-jupyter-kernel#76]
I am wanting to re-install this kernel into my new miniconda3 python 3.9 environment but the install seems to assume a different python setup.

Is there a script for installing into miniconda3 python 3.9 please?

**Comment by rikedyp** [comment]
You need to find the `site-packages` folder for miniconda. 

On Windows, copy:

- the folder `dyalog-kernel` (with a hyphen) into `%APPDATA%\jupyter\kernels\dyalog-kernel`
- the folder `dyalog_kernel` (with an underscore) into `%USERPROFILE%\Miniconda3\Lib\site-packages\dyalog_kernel`

The install scripts will be updated shortly.

**Comment by rikedyp** [comment]
On inspection, `.sh` script should "just work" provided that the `$CONDA_PREFIX` environment variable exists (I had to restart my shell to see it after installing miniconda via the terminal command line).

Windows miniconda path added to `install.bat`: 8b038404a82285bbb2f507fe9d079a6c843e35f2

Noting here also that I'd like to update our docs to correctly reflect just the python and jupyter requirements. Not sure why we recommend Anaconda at all.
