### ISSUE TITLE
Multi-line dfns don't work

### ISSUE THREAD

**Issue by maxrothman** [Dyalog/dyalog-jupyter-kernel#90]
https://github.com/Dyalog/dyalog-jupyter-kernel/issues/32 says it implements multi-line dfns, but they don't work currently:
```apl
%define
dfn←{
⍺+⍵
}

VALUE ERROR: Undefined name: define
      %define
       ∧
SYNTAX ERROR: Unpaired brace
      dfn←{
          ∧
SYNTAX ERROR
      ⍺+⍵
        ∧
SYNTAX ERROR: Unpaired brace
      }
      ∧
```

**Comment by rodrigogiraoserrao** [comment]
Multi-line dfns must be defined in a cell that starts with ]dinput.
This current limitation is documented somewhere, but I don't know where by
heart and on my phone it isn't practical to look for it.

So, a cell with

```
]dinput
dfn←{
⍺+⍵
}
```

Will define addition.
See mastering.dyalog.com for other examples.

**Comment by maxrothman** [comment]
Ah I see, I must've missed that bit in the docs. Thanks!

For future reference, the behavior is documented here: https://github.com/Dyalog/dyalog-jupyter-kernel/wiki/1.1-Creating-content#defining-functions
