### ISSUE TITLE
No obvious way to install without Conda ; this kernel should have a regular `setup.py` and/or be pip-installable (and on Pypi).

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [Dyalog/dyalog-jupyter-kernel#92]
I don't use Conda, and want to avoid it, since I use and develop [Sagemath](https://www.sagemath.org/index.html), which sets up and installs its own virtual environmrnt. In fact, Sage is essentially a (gigantic) venv interfacing Python to a zillion and half mathematical packages.

I tried to mimic manually what `install.sh` does, but my initial attempt failled, jupyter reporting that there was no such kernel.

I finally succeeded by symlinking the two directories `dyalog-kernel`  `dyalog_kernel` to the  "system" directories of the Sage venv. And killed almost a day in the process.

Since Sage supports onstalling "external" Python packages by a simple use of `pip`, the shortest path for me would have to just `pip dyalog-jupyter-kernel`.

I noticed that the Wiki instructions *instst* on getting Conda, but do not explain how it intervenes in the process. A bit of explanatiion would be useful.

HTH,

**Comment by xpqz** [comment]
I came across the same problem. This mod to install.sh fixed it for me:

        if [ -n "$VIRTUAL_ENV" ]; then
                SITEDIR="$VIRTUAL_ENV/lib/python$PYVER/site-packages"
        else
                SITEDIR="$(python3 -m site --user-site)"
        fi

I'll put in a PR.
